In [1]:
# Import necessary libraries
import numpy as np
import matplotlib.pyplot as plt

## Load the data

In [ ]:
data = np.loadtxt('data/ECGu.txt') # Load the ECG data from a text file
print(data) # Print the data to see its structure
print(data.shape) # (number of rows, number of columns)

[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 ...
 [  -4.  -83.   21.]
 [  -9.  -88.   31.]
 [ -16.  -96.   33.]]
(6500, 3)


## Conversion to mV and seconds

In [10]:
ecg_mv = data * 1.024
print(ecg_mv)

[[-281.6   -121.856 -121.856]
 [-281.6   -121.856 -121.856]
 [-281.6   -120.832 -123.904]
 ...
 [  -4.096  -84.992   21.504]
 [  -9.216  -90.112   31.744]
 [ -16.384  -98.304   33.792]]
