In [1]:
# Import necessary libraries
import numpy as np
import matplotlib.pyplot as plt

## Load the data

In [ ]:
data = np.loadtxt('data/ECGu.txt')
print(data) # Print the data to see its structure
print(data.shape) # (number of rows, number of columns)

[[-275. -119. -119.]
 [-275. -119. -119.]
 [-275. -118. -121.]
 ...
 [  -4.  -83.   21.]
 [  -9.  -88.   31.]
 [ -16.  -96.   33.]]
(6500, 3)
